# Generated by Django 4.1.4 on 2023-01-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_alter_links_options_links_count_view_links_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='packets_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(blank=True, max_length=255, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('time_request', models.DurationField(default=0)),
                ('date_request', models.DateTimeField()),
                ('cookie', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'packets log',
                'db_table': 'packets_log',
            },
        ),
    ]
