# Generated by Django 4.1.4 on 2023-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_packets_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packets_log',
            name='date_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
