# Generated by Django 4.1.4 on 2023-01-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0004_alter_packets_log_date_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links_log',
            name='updated_at',
        ),
    ]
