# Generated by Django 4.1.4 on 2023-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0005_remove_links_log_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_log',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
